### ISSUE TITLE
Will it work with CouchDB

### ISSUE THREAD

**Issue by VladimirCores** [MarkMYoung/casbin-couchbase-adapter#7]
Hello. My question is `Will it work with CouchDB`?

**Comment by hsluoyz** [comment]
@VladimirCores does Couchbase have anything to do with CouchDB?

**Comment by VladimirCores** [comment]
It is the ancestor of Couchbase

**Comment by VladimirCores** [comment]
However, it looks like they are not compatible.

**Comment by hsluoyz** [comment]
@VladimirCores if you want a CouchDB adapter, please send issue to: https://github.com/casbin/node-casbin/issues

**Comment by VladimirCores** [comment]
It would be great to have one, requested here https://github.com/casbin/node-casbin/issues/428
Thanks @hsluoyz  ; )

**Comment by MarkMYoung** [comment]
@VladimirCores, there is nothing Couchbase-specific in the `casbin-couchbase-adapter` itself.  To make it work with CouchDB, you would need 1) to extend/replace `PolicyRepository` so that it opens a CouchDB connection (instead of a Coucbase connection) and possibly 2) a CouchDB adapter for `node-casbin` as @hsluoyz suggested.

I'll admit, I should have made `PolicyRepository` implement an interface, but I ran out of time when I was writing it.

**Comment by MarkMYoung** [comment]
@VladimirCores, do you want any help developing a `PolicyRepository` for CouchDB?

**Comment by VladimirCores** [comment]
@MarkMYoung I would like, really, but I should finish what is already started, too many projects.
